server:
  port: 8080


cpf:
  baseUrl: "http://localhost:${server.port}"
  endpoint: "/cpf/{cpf}"

spring:
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ssXXX
    time-zone: America/Sao_Paulo
  application:
    name: votacao

  data:
    mongodb:
      uri: "mongodb://${DB_USER:root}:${DB_PASSWORD:Ora1626X}@${DB_HOST:mongo.redent}:${DB_PORT:27017}"
#      uri: "mongodb://${DB_USER:root}:${DB_PASSWORD:Ora1626X}@${DB_HOST:mongo}:${DB_PORT:27017},${DB_HOST:mongo}:27018,${DB_HOST:mongo}:27019/${DB_NAME:votacao}?authSource=admin&replicaSet=rs0&readPreference=secondaryPreferred"
      authentication-database: "${DB_AUTH_NAME:votacao}"
      database: "${DB_NAME:votacao}"
      auto-index-creation: true
      repositories: true

  # Kafka
  kafka:
    bootstrap-servers: "${KAFKA_BROKERS:kafka:9092}"
    consumer:
      group-id: "${spring.application.name}-group"
#      auto-offset-reset: earliest
      auto-offset-reset: latest
    producer:
      retries: 5
      acks: all
    admin:
      properties:
        topic.replication.factor: 1
